"""GHC 9.14 compatibility Stack lock의 독립 exact-byte 결속을 검사한다."""

from __future__ import annotations

import hashlib
import json
import subprocess
import unittest
from pathlib import Path


TOOLS_ROOT = Path(__file__).resolve().parents[1]
HASKELL_ROOT = TOOLS_ROOT.parent
COMPATIBILITY_LOCK = HASKELL_ROOT / "stack-ghc-9.14.1.yaml.lock"
AUTHORITATIVE_LOCK = HASKELL_ROOT / "stack.yaml.lock"
TOOLCHAIN_LOCK = HASKELL_ROOT / "toolchain-lock.v1.json"
ASSERT_TOOLCHAIN = TOOLS_ROOT / "assert-toolchain.sh"
EXPECTED_LOCK_BYTES = b"""\
# This file was autogenerated by Stack.
# You should not edit this file by hand.
# For more information, please see the documentation at:
#   https://docs.haskellstack.org/en/stable/topics/lock_files

packages: []
snapshots:
- completed:
    sha256: f9f775487e1678844b9f031919ed508a88097aa883002a970d3cd6fc6308b5d2
    size: 732679
    url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/24/50.yaml
  original: lts-24.50
"""


class CompatibilityLockContractTests(unittest.TestCase):
    def test_compatibility_lock_is_tracked_regular_and_exact(self) -> None:
        tracked = subprocess.run(
            [
                "git",
                "-C",
                str(HASKELL_ROOT),
                "ls-files",
                "--error-unmatch",
                "--",
                COMPATIBILITY_LOCK.name,
            ],
            check=False,
            capture_output=True,
            text=True,
        )

        self.assertEqual(tracked.returncode, 0, tracked.stderr)
        self.assertTrue(COMPATIBILITY_LOCK.is_file())
        self.assertFalse(COMPATIBILITY_LOCK.is_symlink())
        self.assertEqual(COMPATIBILITY_LOCK.read_bytes(), EXPECTED_LOCK_BYTES)

    def test_toolchain_lock_hashes_each_stack_lock_from_its_own_bytes(self) -> None:
        document = json.loads(TOOLCHAIN_LOCK.read_text(encoding="utf-8"))
        compatibility_sha256 = hashlib.sha256(
            COMPATIBILITY_LOCK.read_bytes()
        ).hexdigest()
        authoritative_sha256 = hashlib.sha256(
            AUTHORITATIVE_LOCK.read_bytes()
        ).hexdigest()

        self.assertEqual(
            document["compatibilityPlan"]["stackLockSha256"],
            compatibility_sha256,
        )
        self.assertEqual(
            document["stackConfigurations"]["compatibilityLockSha256"],
            compatibility_sha256,
        )
        self.assertEqual(
            document["stackConfigurations"]["authoritativeLockSha256"],
            authoritative_sha256,
        )

    def test_readiness_validator_does_not_alias_the_authoritative_lock_path(
        self,
    ) -> None:
        source = ASSERT_TOOLCHAIN.read_text(encoding="utf-8")

        self.assertIn('"$HASKELL_ROOT/stack-ghc-9.14.1.yaml.lock"', source)
        self.assertIn("compatibility_stack_lock_path", source)
        self.assertIn("sha256(compatibility_stack_lock_path)", source)
        self.assertNotIn(
            '"stackLockSha256": '
            '"e376d075c33c8bc14aebc6f27c6de3a6be81056354a1fc332d71f959f4870154"',
            source,
        )


if __name__ == "__main__":
    unittest.main()
