from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path

from app.data.kis.calendar import previous_xkrx_trading_day
from app.data.kis.http_client import KISHttpClient
from app.data.kis.market_client import KISMarketClient
from app.data.kis.report import SymbolRunResult, write_markdown_report
from app.data.kis.settings import KISSettings
from app.data.kis.storage import missing_daily_ranges, upsert_daily_bars
from app.data.kis.universe import (
    DEFAULT_UNIVERSE_SOURCE,
    UniverseManifest,
    load_symbols_file,
    load_universe_manifest,
    parse_symbols,
)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    settings = KISSettings(kis_data_dir=Path(args.data_dir)) if args.data_dir else KISSettings()
    symbol_resolution = _resolve_symbols(args, settings.data_dir)
    symbols = symbol_resolution.symbols
    requested_end = _parse_date(args.to) if args.to else date.today()
    # S1.1은 다중 소스 캘린더 집계를 구현하지 않고, 로컬 XKRX 판정으로 KIS 호출 여부만 결정한다.
    # 온라인 휴장일에는 client 생성 전 종료해 OAuth/holiday/current/daily endpoint 모두 호출되지 않게 한다.
    end = previous_xkrx_trading_day(requested_end)
    start = _parse_date(args.start) if args.start else _years_before(end, args.years)
    report_path = Path(args.report_path) if args.report_path else settings.data_dir / "reports" / "kis_s1_1_report.md"
    if not settings.offline and requested_end != end:
        # 운영 모드에서는 휴장일에 KIS endpoint를 호출하지 않고 감사 가능한 skipped report만 남긴다.
        write_markdown_report(
            report_path,
            settings=settings,
            symbols=symbols,
            results=[],
            start=start,
            end=end,
            universe_source=symbol_resolution.source,
            universe_manifest=symbol_resolution.manifest,
            holiday_rows=[],
            skipped_reason="Market closed / skipped",
            requested_end=requested_end,
            previous_trading_day=end,
        )
        print(f"KIS S1.1 report written to {report_path}")
        return 0
    client = _build_client(settings)
    try:
        results: list[SymbolRunResult] = []
        for symbol in symbols:
            # 현재가와 일봉을 같은 리포트에 묶어 사람이 smoke 결과와 parquet 증분을 한 번에 대조하게 한다.
            # 주문·잔고성 API는 이 경로에 wiring하지 않아 S1.1 read-only 경계를 코드 구조로도 고정한다.
            current_price = client.current_price(symbol)
            bars = [
                bar
                for range_start, range_end in missing_daily_ranges(settings.data_dir, symbol, start, end)
                for bar in client.daily_bars(symbol, range_start, range_end)
            ]
            upsert = upsert_daily_bars(settings.data_dir, symbol, bars)
            results.append(
                SymbolRunResult(
                    symbol=symbol,
                    current_price=current_price,
                    upsert=upsert,
                    fetched_rows=len(bars),
                )
            )
        # chk-holiday는 live domain supporting read라서 기본 실행에서 빼고, 명시 옵션일 때만 보수적으로 확인한다.
        holiday_rows = client.holidays(requested_end) if args.check_holiday else []
        write_markdown_report(
            report_path,
            settings=settings,
            symbols=symbols,
            results=results,
            start=start,
            end=end,
            universe_source=symbol_resolution.source,
            universe_manifest=symbol_resolution.manifest,
            holiday_rows=holiday_rows,
            requested_end=requested_end,
        )
    finally:
        close = getattr(client, "close", None)
        if callable(close):
            close()
    print(f"KIS S1.1 report written to {report_path}")
    return 0


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backfill KIS S1.1 read-only market data")
    parser.add_argument("--symbols", help="Comma or space separated stock codes. Defaults to KOSPI large-cap seed.")
    parser.add_argument("--symbols-file", help="Text/CSV file. First column is treated as stock code.")
    parser.add_argument("--universe-manifest", help="Universe manifest JSON generated by kis-universe-refresh.")
    parser.add_argument("--years", type=int, default=3)
    parser.add_argument("--from", dest="start")
    parser.add_argument("--to")
    parser.add_argument("--data-dir")
    parser.add_argument("--report-path")
    parser.add_argument("--check-holiday", action="store_true")
    return parser.parse_args(argv)


class _SymbolResolution:
    def __init__(self, symbols: list[str], source: str, manifest: UniverseManifest | None = None) -> None:
        self.symbols = symbols
        self.source = source
        self.manifest = manifest


def _resolve_symbols(args: argparse.Namespace, data_dir: Path) -> _SymbolResolution:
    # 명시 입력은 smoke/debug 의도를 보존하기 위해 항상 최우선이다.
    # 자동 실행은 감사 가능한 universe manifest를 seed보다 먼저 써서 30종목 기준이 리포트에 남게 한다.
    if args.symbols:
        return _SymbolResolution(parse_symbols(args.symbols), "CLI --symbols")
    if args.symbols_file:
        return _SymbolResolution(load_symbols_file(Path(args.symbols_file)), str(args.symbols_file))
    manifest_path = Path(args.universe_manifest) if args.universe_manifest else data_dir / "universe_manifest.json"
    if manifest_path.exists():
        manifest = load_universe_manifest(manifest_path)
        return _SymbolResolution(manifest.symbol_codes, manifest.source_label, manifest)
    return _SymbolResolution(parse_symbols(None), DEFAULT_UNIVERSE_SOURCE)


def _build_client(settings: KISSettings) -> KISMarketClient:
    # online transport/Redis/token limiter wiring은 KISHttpClient private runtime 경계만 소유한다.
    return KISMarketClient(settings, http_client=KISHttpClient(settings))


def _parse_date(value: str) -> date:
    return date.fromisoformat(value)


def _years_before(end: date, years: int) -> date:
    try:
        return end.replace(year=end.year - years)
    except ValueError:
        # 2월 29일 기준 backfill도 CLI가 중단되지 않도록 같은 월의 마지막 안전한 날짜로 낮춘다.
        return end.replace(year=end.year - years, day=28)


if __name__ == "__main__":
    raise SystemExit(main())
