from __future__ import annotations

import argparse
from datetime import date, timedelta
from pathlib import Path

import redis

from app.data.kis.auth import KISTokenManager, RedisLike
from app.data.kis.calendar import previous_xkrx_trading_day
from app.data.kis.http_client import KISHttpClient
from app.data.kis.market_client import KISMarketClient
from app.data.kis.report import SymbolRunResult, write_markdown_report
from app.data.kis.settings import KISSettings
from app.data.kis.storage import upsert_daily_bars
from app.data.kis.universe import (
    DEFAULT_UNIVERSE_SOURCE,
    UniverseManifest,
    load_symbols_file,
    load_universe_manifest,
    parse_symbols,
)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    settings = KISSettings(kis_data_dir=Path(args.data_dir)) if args.data_dir else KISSettings()
    symbol_resolution = _resolve_symbols(args, settings.data_dir)
    symbols = symbol_resolution.symbols
    requested_end = _parse_date(args.to) if args.to else date.today()
    end = previous_xkrx_trading_day(requested_end)
    start = _parse_date(args.start) if args.start else _years_before(end, args.years)
    report_path = Path(args.report_path) if args.report_path else settings.data_dir / "reports" / "kis_s1_1_report.md"
    if not settings.offline and requested_end != end:
        # 운영 모드에서는 휴장일에 KIS endpoint를 호출하지 않고 감사 가능한 skipped report만 남긴다.
        write_markdown_report(
            report_path,
            settings=settings,
            symbols=symbols,
            results=[],
            start=start,
            end=end,
            universe_source=symbol_resolution.source,
            universe_manifest=symbol_resolution.manifest,
            holiday_rows=[],
            skipped_reason="Market closed / skipped",
            requested_end=requested_end,
            previous_trading_day=end,
        )
        print(f"KIS S1.1 report written to {report_path}")
        return 0
    client = _build_client(settings)
    results: list[SymbolRunResult] = []
    for symbol in symbols:
        current_price = client.current_price(symbol)
        bars = client.daily_bars(symbol, start, end)
        upsert = upsert_daily_bars(settings.data_dir, symbol, bars)
        results.append(
            SymbolRunResult(
                symbol=symbol,
                current_price=current_price,
                upsert=upsert,
                fetched_rows=len(bars),
            )
        )
    holiday_rows = client.holidays(requested_end) if args.check_holiday else []
    write_markdown_report(
        report_path,
        settings=settings,
        symbols=symbols,
        results=results,
        start=start,
        end=end,
        universe_source=symbol_resolution.source,
        universe_manifest=symbol_resolution.manifest,
        holiday_rows=holiday_rows,
        requested_end=requested_end,
    )
    print(f"KIS S1.1 report written to {report_path}")
    return 0


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backfill KIS S1.1 read-only market data")
    parser.add_argument("--symbols", help="Comma or space separated stock codes. Defaults to KOSPI large-cap seed.")
    parser.add_argument("--symbols-file", help="Text/CSV file. First column is treated as stock code.")
    parser.add_argument("--universe-manifest", help="Universe manifest JSON generated by kis-universe-refresh.")
    parser.add_argument("--years", type=int, default=3)
    parser.add_argument("--from", dest="start")
    parser.add_argument("--to")
    parser.add_argument("--data-dir")
    parser.add_argument("--report-path")
    parser.add_argument("--check-holiday", action="store_true")
    return parser.parse_args(argv)


class _SymbolResolution:
    def __init__(self, symbols: list[str], source: str, manifest: UniverseManifest | None = None) -> None:
        self.symbols = symbols
        self.source = source
        self.manifest = manifest


def _resolve_symbols(args: argparse.Namespace, data_dir: Path) -> _SymbolResolution:
    # 명시 입력은 smoke/debug 의도를 보존하고, 그 외에는 감사 가능한 manifest를 fallback seed보다 우선한다.
    if args.symbols:
        return _SymbolResolution(parse_symbols(args.symbols), "CLI --symbols")
    if args.symbols_file:
        return _SymbolResolution(load_symbols_file(Path(args.symbols_file)), str(args.symbols_file))
    manifest_path = Path(args.universe_manifest) if args.universe_manifest else data_dir / "universe_manifest.json"
    if manifest_path.exists():
        manifest = load_universe_manifest(manifest_path)
        return _SymbolResolution(manifest.symbol_codes, manifest.source_label, manifest)
    return _SymbolResolution(parse_symbols(None), DEFAULT_UNIVERSE_SOURCE)


def _build_client(settings: KISSettings) -> KISMarketClient:
    redis_client: RedisLike
    if settings.offline:
        # offline fixture 검증은 실제 Redis kis:token을 건드리지 않아 live/mock 토큰 캐시를 보존한다.
        redis_client = _OfflineRedis()
    else:
        redis_client = redis.Redis.from_url(settings.redis_url)
    token_manager = KISTokenManager(settings, redis_client)
    http_client = KISHttpClient(settings)
    return KISMarketClient(settings, http_client=http_client, token_manager=token_manager)


class _OfflineRedis:
    def get(self, name: str) -> None:
        return None

    def set(self, name: str, value: str, ex: int | timedelta | None = None) -> bool | None:
        return None


def _parse_date(value: str) -> date:
    return date.fromisoformat(value)


def _years_before(end: date, years: int) -> date:
    try:
        return end.replace(year=end.year - years)
    except ValueError:
        return end.replace(year=end.year - years, day=28)


if __name__ == "__main__":
    raise SystemExit(main())
