-- 운영에서는 infra/init/02-application-roles.sh가 만드는 role을 Flyway보다 먼저 재현한다.
CREATE ROLE decision_app
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE decision_collector
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO decision_app, decision_collector;
