[project]
name = "capstone-rag-ocr-intel"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "datasets==4.0.0; sys_platform == 'win32'",
  "nncf==2.18.0; sys_platform == 'win32'",
  "numpy==2.2.6",
  "openvino==2026.2.1",
  "pillow==12.3.0",
  "psutil==7.2.2",
  "requests==2.34.2; sys_platform == 'win32'",
  "torch==2.8.0; sys_platform == 'win32'",
  "torchvision==0.23.0; sys_platform == 'win32'",
  "tqdm==4.70.0; sys_platform == 'win32'",
  "transformers==5.10.1; sys_platform == 'win32'"
]

[tool.uv]
package = false
