from __future__ import annotations

import importlib
import os
import sys
import unittest
from pathlib import Path
from unittest.mock import patch

from contracts.generated_artifact_io import GeneratedArtifactWriteError
from contracts.generated_artifact_io import write_generated_artifact
from contracts.generate_principle_contracts import canonical_json_bytes


ROOT = Path(__file__).resolve().parents[2]


class GeneratedArtifactIoTest(unittest.TestCase):
    def test_regular_file_write_and_check_byte_parity(self) -> None:
        with _isolated_root() as root:
            target = root / "contracts/examples/generated.json"
            write_generated_artifact(root, "contracts/examples/generated.json", b"first\n")
            self.assertEqual(b"first\n", target.read_bytes())

            write_generated_artifact(root, "contracts/examples/generated.json", b"second\n")
            self.assertEqual(b"second\n", target.read_bytes())

    def test_unsafe_root_parent_leaf_directory_and_hardlink_are_rejected(self) -> None:
        cases = ("root_symlink", "parent_symlink", "leaf_symlink", "directory", "hardlink")
        for unsafe_kind in cases:
            with self.subTest(unsafe_kind=unsafe_kind), _isolated_root() as parent:
                outside = parent / "outside"
                outside.mkdir()
                sentinel = outside / "sentinel.txt"
                sentinel.write_bytes(b"outside sentinel")
                approved_root = parent / "repo"

                if unsafe_kind == "root_symlink":
                    os.symlink(outside, approved_root)
                else:
                    approved_root.mkdir()

                target = approved_root / "contracts/examples/generated.json"
                if unsafe_kind == "parent_symlink":
                    os.symlink(outside, approved_root / "contracts")
                elif unsafe_kind in {"leaf_symlink", "directory", "hardlink"}:
                    target.parent.mkdir(parents=True)
                    if unsafe_kind == "leaf_symlink":
                        os.symlink(sentinel, target)
                    elif unsafe_kind == "directory":
                        target.mkdir()
                    else:
                        os.link(sentinel, target)

                before = sentinel.read_bytes()
                with self.assertRaises(GeneratedArtifactWriteError):
                    write_generated_artifact(
                        approved_root,
                        "contracts/examples/generated.json",
                        b"generated bytes\n",
                    )
                self.assertEqual(before, sentinel.read_bytes())

    def test_invalid_relative_paths_are_rejected(self) -> None:
        with _isolated_root() as root:
            root.mkdir(exist_ok=True)
            for relative_path in (
                "",
                "/absolute.json",
                "../escape.json",
                "contracts/../escape.json",
                "contracts//escape.json",
                "contracts\\escape.json",
            ):
                with self.subTest(relative_path=relative_path):
                    with self.assertRaises(GeneratedArtifactWriteError):
                        write_generated_artifact(root, relative_path, b"x\n")


class GeneratorWriterIntegrationTest(unittest.TestCase):
    def test_path_mapping_generators_reject_parent_symlink_without_external_mutation(self) -> None:
        for module_name, root_name, writer_name, outputs in _PATH_MAPPING_GENERATORS:
            with self.subTest(module=module_name), _isolated_root() as parent:
                module = importlib.import_module(module_name)
                outside = parent / "outside"
                outside.mkdir()
                sentinel = outside / "sentinel.txt"
                sentinel.write_bytes(b"outside sentinel")
                repo_root = parent / "repo"
                repo_root.mkdir()
                os.symlink(outside, repo_root / "contracts")

                with patch.object(module, root_name, repo_root):
                    before = sentinel.read_bytes()
                    with self.assertRaises(GeneratedArtifactWriteError):
                        getattr(module, writer_name)(outputs(repo_root))
                    self.assertEqual(before, sentinel.read_bytes())

    def test_relative_mapping_generators_reject_parent_symlink_without_external_mutation(self) -> None:
        for module_name, root_name, writer_name, outputs in _RELATIVE_MAPPING_GENERATORS:
            with self.subTest(module=module_name), _isolated_root() as parent:
                module = importlib.import_module(module_name)
                outside = parent / "outside"
                outside.mkdir()
                sentinel = outside / "sentinel.txt"
                sentinel.write_bytes(b"outside sentinel")
                repo_root = parent / "repo"
                repo_root.mkdir()
                os.symlink(outside, repo_root / "contracts")

                with patch.object(module, root_name, repo_root):
                    before = sentinel.read_bytes()
                    with self.assertRaises(GeneratedArtifactWriteError):
                        getattr(module, writer_name)(outputs())
                    self.assertEqual(before, sentinel.read_bytes())

    def test_atomic_path_generators_reject_parent_symlink_without_external_mutation(self) -> None:
        for module_name, root_name, writer_name in _ATOMIC_PATH_GENERATORS:
            with self.subTest(module=module_name), _isolated_root() as parent:
                module = importlib.import_module(module_name)
                outside = parent / "outside"
                outside.mkdir()
                sentinel = outside / "sentinel.txt"
                sentinel.write_bytes(b"outside sentinel")
                repo_root = parent / "repo"
                repo_root.mkdir()
                os.symlink(outside, repo_root / "contracts")

                with patch.object(module, root_name, repo_root):
                    before = sentinel.read_bytes()
                    with self.assertRaises(GeneratedArtifactWriteError):
                        getattr(module, writer_name)(
                            repo_root / "contracts/examples/generated.json",
                            b"generated bytes\n",
                        )
                    self.assertEqual(before, sentinel.read_bytes())

    def test_openapi_normalizer_write_rejects_parent_symlink_without_external_mutation(self) -> None:
        module = importlib.import_module("contracts.normalize_openapi")
        generated = canonical_json_bytes(
            {
                "openapi": "3.1.0",
                "jsonSchemaDialect": "https://spec.openapis.org/oas/3.1/dialect/base",
                "info": {"title": "Decision Platform API", "version": "0"},
                "paths": {},
                "components": {"schemas": {}},
            }
        )
        catalog = canonical_json_bytes({"catalog": "test"})
        for unsafe_kind in ("parent_symlink", "leaf_symlink"):
            with self.subTest(unsafe_kind=unsafe_kind), _isolated_root() as parent:
                outside = parent / "outside"
                outside.mkdir()
                sentinel = outside / "sentinel.txt"
                sentinel.write_bytes(b"outside sentinel")
                repo_root = parent / "repo"
                repo_root.mkdir()
                input_path = repo_root / "build/openapi/generated.json"
                catalog_path = repo_root / "contracts/catalogs/catalog.json"
                expected_path = repo_root / "contracts/openapi/openapi.json"
                input_path.parent.mkdir(parents=True)
                catalog_path.parent.mkdir(parents=True)
                input_path.write_bytes(generated)
                catalog_path.write_bytes(catalog)
                if unsafe_kind == "parent_symlink":
                    os.symlink(outside, repo_root / "contracts/openapi")
                else:
                    expected_path.parent.mkdir(parents=True)
                    os.symlink(sentinel, expected_path)

                argv = [
                    "normalize_openapi",
                    "--write",
                    "--input",
                    str(input_path),
                    "--catalog",
                    str(catalog_path),
                    "--expected",
                    str(expected_path),
                ]
                with (
                    patch.object(module, "REPO_ROOT", repo_root),
                    patch.object(
                        module,
                        "normalize_generated_openapi",
                        return_value=b'{"openapi":"3.1.1"}\n',
                    ),
                    patch.object(module, "_validate_openapi_schema", return_value=None),
                    patch.object(sys, "argv", argv),
                ):
                    before = sentinel.read_bytes()
                    self.assertEqual(1, module.main())
                    self.assertEqual(before, sentinel.read_bytes())

    def test_format_catalog_rejects_leaf_symlink_without_external_mutation(self) -> None:
        for module_name in ("contracts.generate_principle_contracts", "contracts.generate_s2_2_contracts"):
            with self.subTest(module=module_name), _isolated_root() as parent:
                module = importlib.import_module(module_name)
                outside = parent / "outside"
                outside.mkdir()
                sentinel = outside / "sentinel.txt"
                sentinel.write_bytes(canonical_json_bytes({"catalog": "outside"}))
                repo_root = parent / "repo"
                catalog_path = repo_root / "contracts/catalogs/catalog.json"
                catalog_path.parent.mkdir(parents=True)
                os.symlink(sentinel, catalog_path)

                with (
                    patch.object(module, "REPO_ROOT", repo_root),
                    patch.object(module, "CATALOG_PATH", catalog_path),
                    patch.object(module, "load_catalog", return_value={"catalog": "safe"}),
                    patch.object(module, "validate_catalog_semantics", return_value=None),
                ):
                    before = sentinel.read_bytes()
                    with self.assertRaises(GeneratedArtifactWriteError):
                        module._format_catalog()
                    self.assertEqual(before, sentinel.read_bytes())


class _isolated_root:
    def __enter__(self) -> Path:
        import tempfile

        self._directory = tempfile.TemporaryDirectory(dir="/tmp")
        return Path(self._directory.name)

    def __exit__(self, *_: object) -> None:
        self._directory.cleanup()


def _path_outputs(_repo_root: Path) -> dict[Path, bytes]:
    return {
        _repo_root / "contracts/proto/generated.descriptor.pb": b"descriptor\n",
        _repo_root / "contracts/proto/generated.descriptor.sha256": b"0" * 64 + b"\n",
    }


def _relative_outputs() -> dict[str, bytes]:
    return {"contracts/examples/generated.json": b'{"generated":true}\n'}


_PATH_MAPPING_GENERATORS = (
    ("contracts.generate_disclosure_proto", "REPO_ROOT", "_write", _path_outputs),
    ("contracts.generate_rag_proto", "REPO_ROOT", "_write", _path_outputs),
    ("contracts.generate_rag_v2_proto", "REPO_ROOT", "_write", _path_outputs),
)

_RELATIVE_MAPPING_GENERATORS = (
    ("contracts.generate_principle_contracts", "REPO_ROOT", "_write_outputs", _relative_outputs),
    ("contracts.generate_rag_source_card_v2_contracts", "REPO_ROOT", "_write_outputs", _relative_outputs),
    ("contracts.generate_s1_3g_news_contracts", "REPO_ROOT", "_write_outputs", _relative_outputs),
    ("contracts.generate_s2_2_contracts", "REPO_ROOT", "_write_outputs", _relative_outputs),
    ("contracts.generate_s2_3_contracts", "REPO_ROOT", "_write_outputs", _relative_outputs),
    ("contracts.generate_s4_rag_contracts", "REPO_ROOT", "_write_outputs", _relative_outputs),
    ("contracts.generate_s4_7d_rag_v2_contracts", "REPO_ROOT", "_write", _relative_outputs),
    ("contracts.generate_s4_5_provider_contracts", "ROOT", "_write", _relative_outputs),
    ("contracts.generate_s4_8a_cross_market_contracts", "ROOT", "_write_outputs", _relative_outputs),
    ("contracts.generate_s5_0_signal_v2_contracts", "ROOT", "_write_outputs", _relative_outputs),
)

_ATOMIC_PATH_GENERATORS = (
    ("contracts.generate_s3_2_contracts", "REPO_ROOT", "_write_atomic"),
    ("contracts.generate_s3_3_contracts", "REPO_ROOT", "_write_atomic"),
    ("contracts.generate_s4_8a_cross_market_contracts", "ROOT", "_write_atomic"),
    ("contracts.generate_s5_0_signal_v2_contracts", "ROOT", "_write_atomic"),
)


if __name__ == "__main__":
    unittest.main()
