package ai.trading.coach.s14x.core

/** Frozen 19개 production + 13개 research stable error의 closed identifier다. */
enum StableError(val code: String) derives CanEqual:
  case InputTypeInvalid extends StableError("input_type_invalid")
  case InputShapeInvalid extends StableError("input_shape_invalid")
  case InputEmpty extends StableError("input_empty")
  case InputTooShort extends StableError("input_too_short")
  case InputTooLong extends StableError("input_too_long")
  case InputBoolInvalid extends StableError("input_bool_invalid")
  case InputComplexInvalid extends StableError("input_complex_invalid")
  case InputNonFinite extends StableError("input_non_finite")
  case PricesNonPositive extends StableError("prices_non_positive")
  case EquityInitialNonPositive extends StableError("equity_initial_non_positive")
  case EquityNegative extends StableError("equity_negative")
  case SimpleReturnBelowMinusOne extends StableError("simple_return_below_minus_one")
  case PeriodsPerYearInvalid extends StableError("periods_per_year_invalid")
  case RiskFreeRateInvalid extends StableError("risk_free_rate_invalid")
  case TargetReturnInvalid extends StableError("target_return_invalid")
  case ConfidenceInvalid extends StableError("confidence_invalid")
  case DenominatorZero extends StableError("denominator_zero")
  case TailEmpty extends StableError("tail_empty")
  case ResultNonFinite extends StableError("result_non_finite")
  case ResearchInputInvalid extends StableError("research_input_invalid")
  case ResearchInputTooShort extends StableError("research_input_too_short")
  case AggregationPeriodsInvalid extends StableError("aggregation_periods_invalid")
  case MomentInvalid extends StableError("moment_invalid")
  case TrialCountInvalid extends StableError("trial_count_invalid")
  case TrialVarianceInvalid extends StableError("trial_variance_invalid")
  case TrialProvenanceInvalid extends StableError("trial_provenance_invalid")
  case SignificanceInvalid extends StableError("significance_invalid")
  case ForecastShapeInvalid extends StableError("forecast_shape_invalid")
  case ForecastVarNegative extends StableError("forecast_var_negative")
  case InsufficientSample extends StableError("insufficient_sample")
  case LikelihoodInvalid extends StableError("likelihood_invalid")
  case ResearchResultNonFinite extends StableError("research_result_non_finite")
